### ISSUE TITLE
ie带插件安装报错，未安装成功

### ISSUE THREAD

**Issue by huchanghui123** [shellever/quokka-vim#1]
**1. 全新ubuntu16.04,未安装vim**

**2. 下载好quokka-vim**
`
root@hch:~# cd quokka-vim/
`
`
root@hch:~/quokka-vim# ./quokka-vim.sh -ie
`

**3. 安装出错，日志**

option: i
option: e
===> do_config_action_install
===> vim_requirement_setup_ext
./quokka-vim.sh: 行 110: vim: 未找到命令
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
建议安装：
  vim | nvi | vile | emacsen
下列【新】软件包将被安装：
  exuberant-ctags
升级了 0 个软件包，新安装了 1 个软件包，要卸载 0 个软件包，有 103 个软件包未被升级。
需要下载 126 kB 的归档。
解压缩后会消耗 341 kB 的额外空间。
获取:1 http://cn.archive.ubuntu.com/ubuntu xenial/main amd64 exuberant-ctags amd64 1:5.9~svn20110310-11 [126 kB]
已下载 126 kB，耗时 1秒 (64.7 kB/s)       
正在选中未选择的软件包 exuberant-ctags。
(正在读取数据库 ... 系统当前共安装有 215975 个文件和目录。)
正准备解包 .../exuberant-ctags_1%3a5.9~svn20110310-11_amd64.deb  ...
正在解包 exuberant-ctags (1:5.9~svn20110310-11) ...
正在处理用于 man-db (2.7.5-1) 的触发器 ...
正在设置 exuberant-ctags (1:5.9~svn20110310-11) ...
update-alternatives: 使用 /usr/bin/ctags-exuberant 来在自动模式中提供 /usr/bin/ctags (ctags)
update-alternatives: 使用 /usr/bin/ctags-exuberant 来在自动模式中提供 /usr/bin/etags (etags)
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
下列【新】软件包将被安装：
  fonts-powerline
升级了 0 个软件包，新安装了 1 个软件包，要卸载 0 个软件包，有 103 个软件包未被升级。
需要下载 4,572 B 的归档。
解压缩后会消耗 21.5 kB 的额外空间。
获取:1 http://cn.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 fonts-powerline all 2.3-1ubuntu0 [4,572 B]
已下载 4,572 B，耗时 0秒 (6,627 B/s)       
正在选中未选择的软件包 fonts-powerline。
(正在读取数据库 ... 系统当前共安装有 215981 个文件和目录。)
正准备解包 .../fonts-powerline_2.3-1ubuntu0_all.deb  ...
正在解包 fonts-powerline (2.3-1ubuntu0) ...
正在处理用于 fontconfig (2.11.94-0ubuntu1.1) 的触发器 ...
正在设置 fonts-powerline (2.3-1ubuntu0) ...
./quokka-vim.sh: 第 127 行: [: -lt: 需要一元表达式
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
build-essential 已经是最新版 (12.1ubuntu2)。
将会同时安装下列软件：
  libexpat1-dev libpython3-dev libpython3.5-dev python3.5-dev
下列【新】软件包将被安装：
  libexpat1-dev libpython3-dev libpython3.5-dev python3-dev python3.5-dev
升级了 0 个软件包，新安装了 5 个软件包，要卸载 0 个软件包，有 103 个软件包未被升级。
需要下载 37.9 MB 的归档。
解压缩后会消耗 54.9 MB 的额外空间。
获取:1 http://cn.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libexpat1-dev amd64 2.1.0-7ubuntu0.16.04.3 [115 kB]
获取:2 http://cn.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libpython3.5-dev amd64 3.5.2-2ubuntu0~16.04.5 [37.3 MB]
获取:3 http://cn.archive.ubuntu.com/ubuntu xenial/main amd64 libpython3-dev amd64 3.5.1-3 [6,926 B]         
获取:4 http://cn.archive.ubuntu.com/ubuntu xenial-updates/main amd64 python3.5-dev amd64 3.5.2-2ubuntu0~16.04.5 [413 kB]
获取:5 http://cn.archive.ubuntu.com/ubuntu xenial/main amd64 python3-dev amd64 3.5.1-3 [1,186 B]            
已下载 37.9 MB，耗时 8秒 (4,375 kB/s)                                                                       
正在选中未选择的软件包 libexpat1-dev:amd64。
(正在读取数据库 ... 系统当前共安装有 215986 个文件和目录。)
正准备解包 .../libexpat1-dev_2.1.0-7ubuntu0.16.04.3_amd64.deb  ...
正在解包 libexpat1-dev:amd64 (2.1.0-7ubuntu0.16.04.3) ...
正在选中未选择的软件包 libpython3.5-dev:amd64。
正准备解包 .../libpython3.5-dev_3.5.2-2ubuntu0~16.04.5_amd64.deb  ...
正在解包 libpython3.5-dev:amd64 (3.5.2-2ubuntu0~16.04.5) ...
正在选中未选择的软件包 libpython3-dev:amd64。
正准备解包 .../libpython3-dev_3.5.1-3_amd64.deb  ...
正在解包 libpython3-dev:amd64 (3.5.1-3) ...
正在选中未选择的软件包 python3.5-dev。
正准备解包 .../python3.5-dev_3.5.2-2ubuntu0~16.04.5_amd64.deb  ...
正在解包 python3.5-dev (3.5.2-2ubuntu0~16.04.5) ...
正在选中未选择的软件包 python3-dev。
正准备解包 .../python3-dev_3.5.1-3_amd64.deb  ...
正在解包 python3-dev (3.5.1-3) ...
正在处理用于 doc-base (0.10.7) 的触发器 ...
Processing 1 added doc-base file...
正在处理用于 man-db (2.7.5-1) 的触发器 ...
正在设置 libexpat1-dev:amd64 (2.1.0-7ubuntu0.16.04.3) ...
正在设置 libpython3.5-dev:amd64 (3.5.2-2ubuntu0~16.04.5) ...
正在设置 libpython3-dev:amd64 (3.5.1-3) ...
正在设置 python3.5-dev (3.5.2-2ubuntu0~16.04.5) ...
正在设置 python3-dev (3.5.1-3) ...
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
将会同时安装下列软件：
  cmake-data libjsoncpp1
建议安装：
  codeblocks eclipse ninja-build
下列【新】软件包将被安装：
  cmake cmake-data libjsoncpp1
升级了 0 个软件包，新安装了 3 个软件包，要卸载 0 个软件包，有 103 个软件包未被升级。
需要下载 3,817 kB 的归档。
解压缩后会消耗 20.5 MB 的额外空间。
获取:1 http://cn.archive.ubuntu.com/ubuntu xenial-updates/main amd64 cmake-data all 3.5.1-1ubuntu3 [1,121 kB]
获取:2 http://cn.archive.ubuntu.com/ubuntu xenial/main amd64 libjsoncpp1 amd64 1.7.2-1 [73.0 kB]
获取:3 http://cn.archive.ubuntu.com/ubuntu xenial-updates/main amd64 cmake amd64 3.5.1-1ubuntu3 [2,623 kB]
已下载 3,817 kB，耗时 6秒 (605 kB/s)                                                                        
正在选中未选择的软件包 cmake-data。
(正在读取数据库 ... 系统当前共安装有 216161 个文件和目录。)
正准备解包 .../cmake-data_3.5.1-1ubuntu3_all.deb  ...
正在解包 cmake-data (3.5.1-1ubuntu3) ...
正在选中未选择的软件包 libjsoncpp1:amd64。
正准备解包 .../libjsoncpp1_1.7.2-1_amd64.deb  ...
正在解包 libjsoncpp1:amd64 (1.7.2-1) ...
正在选中未选择的软件包 cmake。
正准备解包 .../cmake_3.5.1-1ubuntu3_amd64.deb  ...
正在解包 cmake (3.5.1-1ubuntu3) ...
正在处理用于 man-db (2.7.5-1) 的触发器 ...
正在处理用于 libc-bin (2.23-0ubuntu10) 的触发器 ...
正在设置 cmake-data (3.5.1-1ubuntu3) ...
正在设置 libjsoncpp1:amd64 (1.7.2-1) ...
正在设置 cmake (3.5.1-1ubuntu3) ...
正在处理用于 libc-bin (2.23-0ubuntu10) 的触发器 ...
===> vim_plugin_manager_setup
正克隆到 '/home/laohu/quokka-vim/.vim/bundle/Vundle.vim'...
remote: Enumerating objects: 3136, done.
remote: Total 3136 (delta 0), reused 0 (delta 0), pack-reused 3136
接收对象中: 100% (3136/3136), 933.42 KiB | 48.00 KiB/s, 完成.
处理 delta 中: 100% (1105/1105), 完成.
检查连接... 完成。
===> do_config_action_install_ext
===> do_shadow_before_vim_plugin_install
===> vim_plugin_install
./quokka-vim.sh: 行 161: vim: 未找到命令
===> do_shadow_after_vim_plugin_install
===> ycm_compile_with_c
./quokka-vim.sh: 第 169 行: cd: /home/laohu/quokka-vim/.vim/bundle/YouCompleteMe: 没有那个文件或目录
python3: can't open file 'install.py': [Errno 2] No such file or directory
./quokka-vim.sh: 第 171 行: cd: OLDPWD 未设定

**4.手动安装vim后，再执行./quokka-vim -ie 安装成功！**

**Comment by shellever** [comment]
问题出现的脚本代码片段：
```
function vim_requirement_setup_ext()
{
    ....
    local vim_version=$(vim --version | head -1 | awk '{print $5}')
    local vim_version_major=$(echo "$vim_version" | awk -F. '{print $1}')
    local vim_version_minor=$(echo "$vim_version" | awk -F. '{print $2}')
    ......
    # ycm {{{
    # YouCompleteMe requires Vim 7.4.1578+
    # install vim using source (Vim 8.1)
    if [ $vim_version_major -lt 8 ]; then
        vim_build_from_source
    fi
    ......
}
```
由于在获取版本信息是没有对vim命令是否存在做判断，导致系统未安装过vim时无法找到vim命令的错误，
并且在判断通过编译源码安装vim时，也未对vim是否存在做必要判断，也会导致系统未安装vim时不会自动编译安装最新版本的vim

解决方法是对vim命令的存在进行必要判断，修改如下：
```
function vim_requirement_setup_ext()
{
    ......
    local is_need_vim_build=false
    local vim_version=
    local vim_version_major=
    local vim_version_minor=
    ......
    # ycm {{{
    # YouCompleteMe requires Vim 7.4.1578+
    # install vim using source (Vim 8.1)
    if [ -z "$(which vim)" ]; then
        is_need_vim_build=true
    else
        vim_version=$(vim --version | head -1 | awk '{print $5}')
        vim_version_major=$(echo "$vim_version" | awk -F. '{print $1}')
        vim_version_minor=$(echo "$vim_version" | awk -F. '{print $2}')

        if [ $vim_version_major -lt 8 ]; then
            is_need_vim_build=true
        fi
    fi

    if [ "$is_need_vim_build" = "true" ]; then
        vim_build_from_source
    fi
    ......
}
```

已修改，详见提交记录
good luck 2 u
